AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0f4799f56b9cc2fe9
    Description: Subnet to deploy EC2 instance into
  SecurityGroupIDs:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: sg-0b5221c20834a7df3
    Description: List of Security Groups to add to EC2 instance
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: ansible-test
    Description: >-
      Name of an existing EC2 KeyPair to enable SSH access to the instance
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.medium
  DiskVolume:
    Description: root disk volume
    Type: Number
    Default: 100
  EDRCluster:
    Description: Cluster Name
    Type: String
    Default: edrpreprod
    AllowedValues:
      - edrpreprod
      - edrpreprod-vnext
      - edrusw
      - edrusw-vnext
      - edruse
      - edraps
      - edreuc
      - edrcac
      - edrind
      - spoke-fargate
  BastionName:
    Description: Bastion Name
    Type: String
    Default: edrpreprod-bastion
    AllowedValues:
      - edrpreprod-bastion
      - edrpreprod-vnext-bastion
      - edrusw-bastion-bastion
      - edrusw-vnext-bastion
      - edruse-bastion
      - edraps-bastion
      - edreuc-bastion
      - edrcac-bastion
      - edrind-bastion
      - spoke-fargate-bastion
Mappings:
  AWSRegionToAMI:
    us-west-2:
      AMIID: ami-00af37d1144686454
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    DeletionPolicy: Retain 
    Properties:
      ImageId:
        !FindInMap 
          - AWSRegionToAMI 
          - !Ref AWS::Region
          - AMIID
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroupIDs
      SubnetId: !Ref SubnetID
      IamInstanceProfile: ccs-bastion-prod
      BlockDeviceMappings:
      - DeviceName: "/dev/xvda"
        Ebs:
          VolumeSize: !Ref DiskVolume
      UserData:
        Fn::Base64: 
          !Sub |
              #!/bin/bash -ex
              amazon-linux-extras install epel
              yum update -y
              yum install ansible -y
              yum install nginx -y
              yum install git -y
              systemctl start nginx
              systemctl enable nginx
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              nvm install node
              cat <<EOF >> /home/ec2-user/.bashrc
              export NVM_DIR="/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              EOF
              cd /home/ec2-user
              mkdir server && cd server
              npm install express
      Tags: 
        -
          Key: Name
          Value: !Ref BastionName
        -
          Key: Cluster
          Value: !Ref EDRCluster
        
