---
# This role deploys the python and python dependent packages

- name: Install python3 
  yum:
    name: python3
    state: latest

- name: Install python3-devel 
  yum:
    name: python3-devel
    state: latest
